### PR TITLE
Yl 6 check account 

### PR DESCRIPTION
**Pull request by accardigianni**
CRUD tables, authentication service and fetch data in linkedin profile

### CODE REVIEW

**Comment by C-Alexis4414** [comment]
Please describe precisely, directly in the comment of the PR, what brings functional your enhancement / fix and what remains to be done, instead of just mentioning the subjects you have treated. 
**To be reviewed:** 
_getUrlLinkedinById_ and _verifyLinkedinSkills_. 
Can you add a detailed description of what works and what remains to be seen in response to this comment before merging, please ?

**Comment by accardigianni** [comment]
Add Features:

Subscription
Categories
Tags
Likes
Authentication
Implementation Tasks:

Create controllers for API routes.
Implement methods in services using CRUD queries or primary research queries in the database (many of these may be removed later).
Propose DTOs or interfaces/types to manage data.
Implement foreign keys in the Prisma schema to handle nested data.
Create an API call to retrieve personal LinkedIn skills data.
Set up an authentication folder using JWT services (create registration and login functions, initial implementation of JWT strategy, and AuthGuard).
This pull request is the first step in building the project. Many features and code improvements are missing but will be added in future updates.

**Review by C-Alexis4414 — APPROVED** [review]
Following our code review last Friday, I approve these changes

**Comment by C-Alexis4414** [comment]
close #8

**Pull request merged**
